### ISSUE TITLE
model required

### ISSUE THREAD

**Issue by akks29** [saimj7/People-Counting-in-Real-Time#47]

**Comment by akks29** [comment]
PS C:\Users\usr> python C:\Users\usr\OneDrive\Bureau\People-Counting-in-Real-Time-master/run.py --prototxt mobilenet_ssd/MobileNetSSD_deploy.prototxt --model mobilenet_ssd/MobileNetSSD_deploy.caffemodel --input videos/example_01.mp4
Traceback (most recent call last):
File "C:\Users\usr\OneDrive\Bureau\People-Counting-in-Real-Time-master\run.py", line 349, in
run()
File "C:\Users\usrs\OneDrive\Bureau\People-Counting-in-Real-Time-master\run.py", line 42, in run
net = cv2.dnn.readNetFromCaffe(args["prototxt"], args["model"])
cv2.error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-wvn_it83\opencv\modules\dnn\src\caffe\caffe_io.cpp:1121: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "mobilenet_ssd/MobileNetSSD_deploy.prototxt" in function 'cv::dnn::ReadProtoFromTextFile'


i'm receiving this error..all my packages are up to date

**Comment by CharlesDahl** [comment]
Have you tried:
python run.py --prototxt mobilenet_ssd/MobileNetSSD_deploy.prototxt --model mobilenet_ssd/MobileNetSSD_deploy.caffemodel --input videos/example_01.mp4 ?

**Comment by akks29** [comment]
yes..and this error comes up
-Can't open "mobilenet_ssd/MobileNetSSD_deploy.prototxt" in function 'cv::dnn::ReadProtoFromTextFile'

**Comment by akks29** [comment]
what should be done now?

**Comment by CharlesDahl** [comment]
I think you need to install cmake package, here is the link: https://pypi.org/project/cmake/.

**Comment by akks29** [comment]
CMake is already installed.

**Comment by akks29** [comment]
and OpenCV is working on other projects.
Is there a problem with the model being used?

**Comment by CharlesDahl** [comment]
Which version of Python are you using?

**Comment by akks29** [comment]
3.10

**Comment by CharlesDahl** [comment]
I think this project doesn't work on 3.10, I have 3.9 and it worked for me. I didn't succeed running the project in 3.10.

**Comment by akks29** [comment]
oh okk

**Comment by akks29** [comment]
It works now!
thanks.
